volumes:
  db-data:

services:
  db:
    image: postgres:15-alpine
    container_name: rent-contracts-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rent-contracts
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./scripts/seed.sql:/docker-entrypoint-initdb.d/seed.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 1s
      retries: 5

  api:
    container_name: rent-contracts-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: rent-contracts
      DB_SSLMODE: disable
      PORT: 8080
      GIN_MODE: release
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
  web:
    container_name: rent-contracts-web
    build:
      context: web
      dockerfile: Dockerfile
    ports:
      - "3000:5173"
