openapi: 3.0.3
info:
  title: Rent Contracts API
  version: 1.0.0
  description: API for managing rental contracts, addresses, users, and contract versions.
servers:
  - url: http://localhost:8080
paths:
  /api/v1/addresses:
    get:
      tags: [Addresses]
      summary: Get all addresses
      responses:
        '200':
          description: List of addresses
    post:
      tags: [Addresses]
      summary: Create a new address
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddressInput'
      responses:
        '201':
          description: Address created
  /api/v1/addresses/{id}:
    get:
      tags: [Addresses]
      summary: Get address by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Address found
    put:
      tags: [Addresses]
      summary: Update address
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddressInput'
      responses:
        '200':
          description: Address updated
    delete:
      tags: [Addresses]
      summary: Delete address
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Address deleted
  /api/v1/users:
    get:
      tags: [Users]
      summary: Get all users
      responses:
        '200':
          description: List of users
    post:
      tags: [Users]
      summary: Create a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserInput'
      responses:
        '201':
          description: User created
  /api/v1/users/{id}:
    get:
      tags: [Users]
      summary: Get user by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: User found
    put:
      tags: [Users]
      summary: Update user
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserInput'
      responses:
        '200':
          description: User updated
    delete:
      tags: [Users]
      summary: Delete user
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '204':
          description: User deleted
  /api/v1/contracts:
    get:
      tags: [Contracts]
      summary: Get all contracts
      responses:
        '200':
          description: List of contracts
    post:
      tags: [Contracts]
      summary: Create a new contract
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ContractInput'
      responses:
        '201':
          description: Contract created
  /api/v1/contracts/{id}:
    get:
      tags: [Contracts]
      summary: Get contract by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Contract found
    put:
      tags: [Contracts]
      summary: Update contract
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ContractInput'
      responses:
        '200':
          description: Contract updated
    delete:
      tags: [Contracts]
      summary: Delete contract
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Contract deleted
  /api/v1/contracts/versions:
    post:
      tags: [Contract Versions]
      summary: Create a new contract version
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ContractVersionInput'
      responses:
        '201':
          description: Contract version created
  /api/v1/contracts/{id}/versions:
    get:
      tags: [Contract Versions]
      summary: Get contract versions by contract ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: List of contract versions
components:
  schemas:
    AddressInput:
      type: object
      properties:
        type:
          type: string
        street:
          type: string
        number:
          type: string
        neighborhood:
          type: string
        city:
          type: string
        state:
          type: string
        zipCode:
          type: string
        country:
          type: string
    UserInput:
      type: object
      properties:
        type:
          type: string
        addressId:
          type: string
        firstName:
          type: string
        middleName:
          type: string
        lastName:
          type: string
        email:
          type: string
        phone:
          type: string
    ContractInput:
      type: object
      properties:
        tenantId:
          type: string
        addressId:
          type: string
    ContractVersionInput:
      type: object
      properties:
        contractId:
          type: string
        versionNumber:
          type: integer
        deposit:
          type: number
        rent:
          type: number
        rentIncreasePercentage:
          type: number
        business:
          type: string
        status:
          type: string
        type:
          type: string
        startDate:
          type: string
          format: date
        endDate:
          type: string
          format: date
        renewalDate:
          type: string
          format: date
        specialTerms:
          type: string
